name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build vsix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use latest Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: build
        run: |
          yarn
          yarn build
        env:
          CI: true
