name: Publish

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    name: publish vsix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use latest Node.js
        uses: actions/setup-node@v1
      - name: publish
        run: |
          yarn
          yarn bundle
          yarn publish-bundle -p ${{ secrets.vscepublishtoken }}
      - name: generate changes
        run: git show  CHANGELOG.md | egrep "^\+" | tail +5 | sed -e 's/^\+//' > changelog.txt
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelog.txt
          files: |
            custom-theme.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.vscepublishtoken }}
