name: CI

on: 
  push: 
    branches: 
      - master
    paths: 
      - 'themes/*'
      - 'package.json'

jobs:
  build:
    name: publish vsix
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use latest Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: publish
      run: |
        yarn
        yarn vsce publish
      env:
        vscepublishtoken: ${{ secrets.vscepublishtoken }}
