name: Publish

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    name: publish vsix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use latest Node.js
        uses: actions/setup-node@v1
      - name: publish
        run: |
          yarn
          yarn bundle
          yarn publish-bundle
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            custom-theme.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.vscepublishtoken }}
